services:
  agent-orcha:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - ./templates:/data
    environment:
      PORT: 3333
      NODE_ENV: development
      VITE_DEV: "false"
      BROWSER_SANDBOX: "true"
      AUTH_PASSWORD: ${AUTH_PASSWORD:-}
    shm_size: "2gb"
    cap_add:
      - SYS_ADMIN
    develop:
      watch:
        - action: sync
          path: ./lib
          target: /app/lib
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./public
          target: /app/public
